# Generated by Django 5.0.7 on 2025-04-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Category URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2555, null=True)),
                ('slug', models.SlugField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Material URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=9990, null=True)),
                ('code', models.TextField(blank=True, max_length=9990, null=True)),
                ('image', models.FileField(null=True, upload_to='imagefolder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_snippet', to='Products.material')),
            ],
        ),
    ]
